"""Add degree tracker tables

Revision ID: 21ddc6f57033
Revises: 43f1474324bf
Create Date: 2026-01-19 21:39:53.754152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ddc6f57033'
down_revision: Union[str, Sequence[str], None] = '43f1474324bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degree_programs',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('target_grade', sa.Float(), nullable=True),
    sa.Column('total_credits_required', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', 'DEFERRED', name='degreestatus'), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_degree_programs_created_at'), 'degree_programs', ['created_at'], unique=False)
    op.create_index(op.f('ix_degree_programs_id'), 'degree_programs', ['id'], unique=True)
    op.create_index(op.f('ix_degree_programs_user_id'), 'degree_programs', ['user_id'], unique=False)
    op.create_table('modules',
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('weighting', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('UPCOMING', 'IN_PROGRESS', 'COMPLETED', name='modulestatus'), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['degree_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_created_at'), 'modules', ['created_at'], unique=False)
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=True)
    op.create_index(op.f('ix_modules_program_id'), 'modules', ['program_id'], unique=False)
    op.create_table('coursework',
    sa.Column('module_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('weighting', sa.Float(), nullable=False),
    sa.Column('max_marks', sa.Float(), nullable=True),
    sa.Column('achieved_marks', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'GRADED', name='courseworkstatus'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('graded_at', sa.DateTime(), nullable=True),
    sa.Column('feedback', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coursework_created_at'), 'coursework', ['created_at'], unique=False)
    op.create_index(op.f('ix_coursework_id'), 'coursework', ['id'], unique=True)
    op.create_index(op.f('ix_coursework_module_id'), 'coursework', ['module_id'], unique=False)
    op.alter_column('calendar_items', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('calendar_items', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('events', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('events', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('trigger_executions', 'trigger_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('trigger_executions', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('triggers', 'calendar_item_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('triggers', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('triggers', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('triggers', 'calendar_item_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('trigger_executions', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('trigger_executions', 'trigger_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('events', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('events', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('calendar_items', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('calendar_items', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index(op.f('ix_coursework_module_id'), table_name='coursework')
    op.drop_index(op.f('ix_coursework_id'), table_name='coursework')
    op.drop_index(op.f('ix_coursework_created_at'), table_name='coursework')
    op.drop_table('coursework')
    op.drop_index(op.f('ix_modules_program_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_created_at'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_degree_programs_user_id'), table_name='degree_programs')
    op.drop_index(op.f('ix_degree_programs_id'), table_name='degree_programs')
    op.drop_index(op.f('ix_degree_programs_created_at'), table_name='degree_programs')
    op.drop_table('degree_programs')
    # ### end Alembic commands ###
