"""Initial migration with users, events, calendar_items, triggers, and trigger_executions tables

Revision ID: 43f1474324bf
Revises: 
Create Date: 2026-01-19 21:27:10.874538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '43f1474324bf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('calendar_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('EVENT', 'TASK', 'REMINDER', name='calendaritemtype'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('estimated_duration', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Integer(), nullable=False),
    sa.Column('recurrence_rule', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='calendaritemstatus'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('estimated_duration IS NULL OR estimated_duration > 0', name='check_estimated_duration_positive'),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='check_progress_percent_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_items_created_at'), 'calendar_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_calendar_items_id'), 'calendar_items', ['id'], unique=True)
    op.create_index('ix_calendar_items_start_time', 'calendar_items', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_items_status'), 'calendar_items', ['status'], unique=False)
    op.create_index(op.f('ix_calendar_items_type'), 'calendar_items', ['type'], unique=False)
    op.create_index(op.f('ix_calendar_items_user_id'), 'calendar_items', ['user_id'], unique=False)
    op.create_index('ix_calendar_items_user_status', 'calendar_items', ['user_id', 'status'], unique=False)
    op.create_index('ix_calendar_items_user_type', 'calendar_items', ['user_id', 'type'], unique=False)
    op.create_table('events',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_created_at', 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=True)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_index('ix_events_user_type', 'events', ['user_id', 'type'], unique=False)
    op.create_table('triggers',
    sa.Column('calendar_item_id', sa.UUID(), nullable=False),
    sa.Column('trigger_type', sa.Enum('TIME', 'LOCATION', 'PROGRESS', 'NFC', name='triggertype'), nullable=False),
    sa.Column('trigger_config', postgresql.JSON(astext_type=Text()), nullable=False),
    sa.Column('last_fired_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_item_id'], ['calendar_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_triggers_active', 'triggers', ['is_active'], unique=False)
    op.create_index(op.f('ix_triggers_calendar_item_id'), 'triggers', ['calendar_item_id'], unique=False)
    op.create_index('ix_triggers_calendar_item_type', 'triggers', ['calendar_item_id', 'trigger_type'], unique=False)
    op.create_index(op.f('ix_triggers_created_at'), 'triggers', ['created_at'], unique=False)
    op.create_index(op.f('ix_triggers_id'), 'triggers', ['id'], unique=True)
    op.create_index(op.f('ix_triggers_is_active'), 'triggers', ['is_active'], unique=False)
    op.create_index(op.f('ix_triggers_trigger_type'), 'triggers', ['trigger_type'], unique=False)
    op.create_table('trigger_executions',
    sa.Column('trigger_id', sa.UUID(), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILURE', name='triggerexecutionstatus'), nullable=False),
    sa.Column('result', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_executions_created_at'), 'trigger_executions', ['created_at'], unique=False)
    op.create_index(op.f('ix_trigger_executions_fired_at'), 'trigger_executions', ['fired_at'], unique=False)
    op.create_index(op.f('ix_trigger_executions_id'), 'trigger_executions', ['id'], unique=True)
    op.create_index('ix_trigger_executions_status', 'trigger_executions', ['status'], unique=False)
    op.create_index('ix_trigger_executions_trigger_fired', 'trigger_executions', ['trigger_id', 'fired_at'], unique=False)
    op.create_index(op.f('ix_trigger_executions_trigger_id'), 'trigger_executions', ['trigger_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_executions_trigger_id'), table_name='trigger_executions')
    op.drop_index('ix_trigger_executions_trigger_fired', table_name='trigger_executions')
    op.drop_index('ix_trigger_executions_status', table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_id'), table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_fired_at'), table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_created_at'), table_name='trigger_executions')
    op.drop_table('trigger_executions')
    op.drop_index(op.f('ix_triggers_trigger_type'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_is_active'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_id'), table_name='triggers')
    op.drop_index(op.f('ix_triggers_created_at'), table_name='triggers')
    op.drop_index('ix_triggers_calendar_item_type', table_name='triggers')
    op.drop_index(op.f('ix_triggers_calendar_item_id'), table_name='triggers')
    op.drop_index('ix_triggers_active', table_name='triggers')
    op.drop_table('triggers')
    op.drop_index('ix_events_user_type', table_name='events')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_index('ix_events_created_at', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_calendar_items_user_type', table_name='calendar_items')
    op.drop_index('ix_calendar_items_user_status', table_name='calendar_items')
    op.drop_index(op.f('ix_calendar_items_user_id'), table_name='calendar_items')
    op.drop_index(op.f('ix_calendar_items_type'), table_name='calendar_items')
    op.drop_index(op.f('ix_calendar_items_status'), table_name='calendar_items')
    op.drop_index('ix_calendar_items_start_time', table_name='calendar_items')
    op.drop_index(op.f('ix_calendar_items_id'), table_name='calendar_items')
    op.drop_index(op.f('ix_calendar_items_created_at'), table_name='calendar_items')
    op.drop_table('calendar_items')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
